# Generated by Django 3.1.7 on 2021-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_no',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='my address', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(default='State Your Bank', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='bvn',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Select Gender', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Select Gender', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='guarantor',
            field=models.CharField(default='guarantor name', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='guarantor_phone_no',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
