# Generated by Django 3.1.7 on 2021-03-15 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=10)),
                ('loan_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='loan_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
    ]
