# Generated by Django 3.1.7 on 2021-03-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('6', '6 Months'), ('12', '12 Months'), ('15', '15 Months'), ('24', '24 Months')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=30),
        ),
    ]
