# Generated by Django 3.1.7 on 2021-03-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20210317_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(default='Group 1', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='loan.group'),
        ),
    ]
