# Generated by Django 3.1.7 on 2021-03-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20210317_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.AlterField(
            model_name='lender',
            name='group',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='loan.group'),
        ),
    ]
