# Generated by Django 3.1.7 on 2021-03-18 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0006_auto_20210317_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekly_Repayment',
            new_name='Week',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='week',
            new_name='week_date',
        ),
    ]
