# Generated by Django 3.1.7 on 2021-03-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20210318_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='owner',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.lender'),
        ),
    ]
