# Generated by Django 3.1.7 on 2021-03-18 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0009_auto_20210318_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('s', 'Select')], default='select', max_length=20)),
                ('phone', models.CharField(max_length=15, null='blank')),
                ('email', models.EmailField(max_length=254, null='blank', unique=True)),
                ('username', models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null='blank')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('loan_amount', models.CharField(default='100000', max_length=30, null='blank')),
                ('loan_duration', models.PositiveIntegerField(default='6')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=30)),
                ('description', models.TextField()),
                ('frequency', models.IntegerField(blank=True, default=0)),
                ('group', models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='loan.group')),
                ('owner', models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='loan.client')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.RemoveField(
            model_name='week',
            name='owner',
        ),
        migrations.AddField(
            model_name='week',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AddField(
            model_name='week',
            name='principal',
            field=models.IntegerField(default='100000'),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Lender',
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='loan.client'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='week',
            name='which_loan',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
            preserve_default='blank',
        ),
    ]
