# Generated by Django 3.1.7 on 2021-03-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_auto_20210319_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='which_loan',
        ),
        migrations.AddField(
            model_name='week',
            name='which_loan',
            field=models.ManyToManyField(to='loan.Loan'),
        ),
    ]
