# Generated by Django 3.1.7 on 2021-03-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_week_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
    ]
