# Generated by Django 3.1.7 on 2021-03-19 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0014_remove_group_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, null='blank')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('tot_principal', models.CharField(max_length=30, null='blank')),
                ('tot_interest', models.CharField(max_length=30, null='blank')),
                ('group', models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group')),
            ],
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='Collector',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_amount',
            new_name='principal',
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
        migrations.AddField(
            model_name='payment',
            name='which_loan',
            field=models.ManyToManyField(to='loan.Loan'),
        ),
    ]
