# Generated by Django 3.1.7 on 2021-03-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_auto_20210319_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loan.loan'),
            preserve_default='blank',
        ),
    ]
