# Generated by Django 3.1.7 on 2021-03-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_payment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='loan.collector'),
            preserve_default='blank',
        ),
    ]
