# Generated by Django 3.1.7 on 2021-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_auto_20210319_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='tot_interest',
            field=models.CharField(max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='loan',
            name='tot_principal',
            field=models.CharField(max_length=30, null='blank'),
            preserve_default='blank',
        ),
    ]
