# Generated by Django 3.1.7 on 2021-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_auto_20210320_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tot_interest',
            field=models.CharField(default=0, max_length=30, null='blank'),
        ),
    ]
