# Generated by Django 3.1.7 on 2021-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0021_auto_20210320_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='principal',
            field=models.CharField(default=100000, max_length=30, null='blank'),
        ),
    ]
