# Generated by Django 3.1.7 on 2021-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_auto_20210320_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal',
            field=models.IntegerField(default=100000, null='blank'),
        ),
    ]
