# Generated by Django 3.1.7 on 2021-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_auto_20210320_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(default=0.1),
        ),
    ]
