# Generated by Django 3.1.7 on 2021-03-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_auto_20210320_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance',
            field=models.IntegerField(default=0, null='blank'),
            preserve_default='blank',
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('loan_month', models.ForeignKey(default=1, null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
    ]
