# Generated by Django 3.1.7 on 2021-03-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0025_auto_20210320_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='frequency',
            field=models.IntegerField(blank=True, default=6),
        ),
    ]
