# Generated by Django 3.1.7 on 2021-03-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0026_auto_20210320_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='loan_month',
            field=models.ForeignKey(default=6, null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
