# Generated by Django 3.1.7 on 2021-03-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_auto_20210320_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.CharField(default=6, max_length=10),
        ),
    ]
