# Generated by Django 3.1.7 on 2021-03-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0028_auto_20210320_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
