# Generated by Django 3.1.7 on 2021-03-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0029_auto_20210321_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=6),
        ),
    ]
