# Generated by Django 3.1.7 on 2021-03-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0030_auto_20210321_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='frequency',
            field=models.IntegerField(default=6, null='blank'),
        ),
    ]
