# Generated by Django 3.1.4 on 2021-03-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0031_auto_20210322_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='frequency',
            field=models.IntegerField(default=5, null='blank'),
        ),
    ]
