# Generated by Django 3.1.4 on 2021-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0032_auto_20210325_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tot_interest',
            field=models.FloatField(default=0.0, max_length=30, null='blank'),
        ),
    ]
