# Generated by Django 3.1.4 on 2021-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0033_auto_20210325_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='balance',
            field=models.FloatField(default=0, null='blank'),
        ),
    ]
