# Generated by Django 3.1.4 on 2021-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0034_auto_20210325_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='frequency',
            field=models.IntegerField(default=6, null='blank'),
        ),
    ]
