# Generated by Django 3.1.7 on 2021-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0035_auto_20210325_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
        migrations.AddField(
            model_name='loan',
            name='check_request',
            field=models.CharField(choices=[('Unapproved', 'Unapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='incomplete', max_length=30),
        ),
    ]
