# Generated by Django 3.1.7 on 2021-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0036_auto_20210409_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='slug',
            field=models.SlugField(default='title', max_length=200),
        ),
    ]
