# Generated by Django 3.1.7 on 2021-04-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0037_loan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='which_loan',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='check_request',
            new_name='loan_request',
        ),
        migrations.AlterField(
            model_name='loan',
            name='balance',
            field=models.FloatField(default=100000, null='blank'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(default='group ?', null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='loan.group'),
        ),
        migrations.AlterIndexTogether(
            name='loan',
            index_together={('id', 'slug')},
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
