# Generated by Django 3.1.7 on 2021-04-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0038_auto_20210410_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(default='None', null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='loan.group'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=30),
        ),
    ]
