# Generated by Django 3.2 on 2023-01-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0039_auto_20210410_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(default=2, null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='loan.group'),
        ),
    ]
