# Generated by Django 3.1.7 on 2021-03-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_auto_20210320_2129'),
        ('month', '0002_auto_20210320_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='month1',
            name='name',
            field=models.CharField(default='month 1', max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month2',
            name='name',
            field=models.CharField(default='month 2', max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month3',
            name='name',
            field=models.CharField(default='month 3', max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month4',
            name='name',
            field=models.CharField(default='month 4', max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month5',
            name='name',
            field=models.CharField(default='month 5', max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month6',
            name='name',
            field=models.CharField(default='month 6', max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month7',
            name='name',
            field=models.CharField(default='month 7', max_length=30, null='blank'),
            preserve_default='blank',
        ),
        migrations.AlterField(
            model_name='month1',
            name='loan_month1',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month2',
            name='loan_month2',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month3',
            name='loan_month3',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month4',
            name='loan_month4',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month5',
            name='loan_month5',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month6',
            name='loan_month6',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month7',
            name='loan_month7',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
