# Generated by Django 3.1.7 on 2021-03-20 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_auto_20210320_2129'),
        ('month', '0003_auto_20210320_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='month1',
            name='loan_group1',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month2',
            name='loan_group2',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month3',
            name='loan_group3',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month4',
            name='loan_group4',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month5',
            name='loan_group5',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month6',
            name='loan_group6',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group'),
            preserve_default='blank',
        ),
        migrations.AddField(
            model_name='month7',
            name='loan_group7',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.group'),
            preserve_default='blank',
        ),
    ]
