# Generated by Django 3.1.7 on 2021-03-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_auto_20210320_2129'),
        ('month', '0004_auto_20210320_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month1',
            name='loan_month1',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan', unique=True),
        ),
        migrations.AlterField(
            model_name='month2',
            name='loan_month2',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan', unique=True),
        ),
        migrations.AlterField(
            model_name='month3',
            name='loan_month3',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan', unique=True),
        ),
        migrations.AlterField(
            model_name='month4',
            name='loan_month4',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan', unique=True),
        ),
        migrations.AlterField(
            model_name='month5',
            name='loan_month5',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan', unique=True),
        ),
        migrations.AlterField(
            model_name='month6',
            name='loan_month6',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan', unique=True),
        ),
        migrations.AlterField(
            model_name='month7',
            name='loan_month7',
            field=models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan', unique=True),
        ),
    ]
