# Generated by Django 3.1.7 on 2021-03-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0031_auto_20210322_2058'),
        ('month', '0005_auto_20210320_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='month1',
            name='paid_date',
            field=models.DateTimeField(null='blank'),
            preserve_default='blank',
        ),
        migrations.AlterField(
            model_name='month1',
            name='loan_month1',
            field=models.OneToOneField(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
