# Generated by Django 3.1.4 on 2021-03-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0031_auto_20210322_2058'),
        ('month', '0006_auto_20210322_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month2',
            name='loan_month2',
            field=models.OneToOneField(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month3',
            name='loan_month3',
            field=models.OneToOneField(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month4',
            name='loan_month4',
            field=models.OneToOneField(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month5',
            name='loan_month5',
            field=models.OneToOneField(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month6',
            name='loan_month6',
            field=models.OneToOneField(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='month7',
            name='loan_month7',
            field=models.OneToOneField(null='blank', on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
